### PR TITLE
Wizzy

### PR DESCRIPTION
**Pull request by mitchellblom**
@blairvansant @OwenHerndon meeting all requirements here I believe. Page clears upon backspace in the input textbox. Bio text still bound to input even when another is clicked. Is that the intent?

### CODE REVIEW

**Comment by mitchellblom** [comment]
@blairvansant @OwenHerndon should be completely good to go now. Try to break it and see if I missed anything!

**Comment by mitchellblom** [comment]
Clearly still needs readme, but waiting till all okay before taking screenshot, finalizing readme

**Comment by mitchellblom** [comment]
@blairvansant @OwenHerndon Enter key now saving bio just fine between edits, but clicking between them copies the current bio into the previous one. Feel like I'm only missing one line somewhere. Thoughts?

**Comment by mitchellblom** [comment]
@blairvansant @OwenHerndon Readme now complete. Should be good to go! Please review and approve if all good.

**Comment by OwenHerndon** [comment]
This looks great, nice touch being able to target different elements to edit them plus validating the code to only allow the user to edit the clicked element.

Good job 👍

**Comment by mitchellblom** [comment]
Thanks! merging

**Pull request merged**
